name: Deploy Project 1 (PHP) to Somee

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Project1_PHP/**' # Chá»‰ cháº¡y khi sá»­a code trong folder nÃ y

jobs:
  deploy-php:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Láº¥y code má»›i nháº¥t
        uses: actions/checkout@v3

      - name: ğŸ“‚ Upload file qua FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Folder chá»©a code á»Ÿ mÃ¡y mÃ¬nh
          local-dir: ./Project1_PHP/
          # Folder trÃªn Server (QUAN TRá»ŒNG: VÃ o Somee File Manager xem Ä‘Ãºng Ä‘Æ°á»ng dáº«n)
          server-dir: /
